#!/usr/bin/env bash

# Filename for the current number of solutions
SOLUTIONS="solutions.txt"

# Filenames for the javascript files
INDEX="index.js"
ISEVEN="isEven.js"

# Read the number of solutions from that file name
# and then increment that number.
NUMBER_SOLUTIONS=$(awk '{print $1}' ${SOLUTIONS})
NUMBER_SOLUTIONS=$((NUMBER_SOLUTIONS+1))
echo -n ${NUMBER_SOLUTIONS} > ${SOLUTIONS}

mkdir -p ${NUMBER_SOLUTIONS}
cd ${NUMBER_SOLUTIONS}

touch "index.js"
touch "isEven.js"

# to prevent errors
CONSOLE_LOG='console.log(` [${i}]: ${isEven(i)}`);'

cat > $INDEX <<- EOM
// DO NOT EDIT THIS FILE!
const isEven = require("./isEven.js").default;

console.log(" ================ SOLUTION # $NUMBER_SOLUTIONS")

for (let i = 0; i < 10; i++) {
    $CONSOLE_LOG
}

console.log(" ================ END SOLUTION # $NUMBER_SOLUTIONS")
EOM

cat > $ISEVEN <<- EOM

module.exports.default = (number) => {
    // your code.
    // note: visit r/programmerhumor for ideas!
}
EOM

cd ..